openapi: 3.0.0
info:
  title: Gmail API
  description: "The Gmail API lets you view and manage Gmail mailbox data like threads,\
    \ messages, and labels."
  termsOfService: https://developers.google.com/terms/
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  version: v1
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
  x-origin:
  - format: google
    url: https://gmail.googleapis.com/$discovery/rest?version=v1
    version: v1
  x-providerName: googleapis.com
  x-serviceName: gmail
servers:
- url: https://gmail.googleapis.com/gmail/v1
tags:
- name: users
paths:
  /users/{userId}/drafts:
    get:
      tags:
      - users
      description: Lists the drafts in the user's mailbox.
      operationId: gmail.users.drafts.list
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.compose
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.compose
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.readonly
    post:
      tags:
      - users
      description: Creates a new draft with the `DRAFT` label.
      operationId: gmail.users.drafts.create
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.addons.current.action.compose
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.addons.current.action.compose
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.compose
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.compose
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
  /users/{userId}/drafts/send:
    post:
      tags:
      - users
      description: "Sends the specified, existing draft to the recipients in the `To`,\
        \ `Cc`, and `Bcc` headers."
      operationId: gmail.users.drafts.send
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.addons.current.action.compose
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.addons.current.action.compose
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.compose
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.compose
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
  /users/{userId}/drafts/{id}:
    get:
      tags:
      - users
      description: Gets the specified draft.
      operationId: gmail.users.drafts.get
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.compose
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.compose
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.readonly
    put:
      tags:
      - users
      description: Replaces a draft's content.
      operationId: gmail.users.drafts.update
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.addons.current.action.compose
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.addons.current.action.compose
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.compose
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.compose
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
    delete:
      tags:
      - users
      description: Immediately and permanently deletes the specified draft. Does not
        simply trash it.
      operationId: gmail.users.drafts.delete
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.addons.current.action.compose
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.addons.current.action.compose
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.compose
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.compose
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
  /users/{userId}/history:
    get:
      tags:
      - users
      description: Lists the history of all changes to the given mailbox. History
        results are returned in chronological order (increasing `historyId`).
      operationId: gmail.users.history.list
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.readonly
  /users/{userId}/labels:
    get:
      tags:
      - users
      description: Lists all labels in the user's mailbox.
      operationId: gmail.users.labels.list
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.labels
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.labels
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.readonly
    post:
      tags:
      - users
      description: Creates a new label.
      operationId: gmail.users.labels.create
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.labels
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.labels
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
  /users/{userId}/labels/{id}:
    get:
      tags:
      - users
      description: Gets the specified label.
      operationId: gmail.users.labels.get
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.labels
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.labels
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.readonly
    put:
      tags:
      - users
      description: Updates the specified label.
      operationId: gmail.users.labels.update
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.labels
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.labels
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
    delete:
      tags:
      - users
      description: Immediately and permanently deletes the specified label and removes
        it from any messages and threads that it is applied to.
      operationId: gmail.users.labels.delete
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.labels
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.labels
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
    patch:
      tags:
      - users
      description: Patch the specified label.
      operationId: gmail.users.labels.patch
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.labels
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.labels
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
  /users/{userId}/messages:
    get:
      tags:
      - users
      description: Lists the messages in the user's mailbox.
      operationId: gmail.users.messages.list
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.readonly
    post:
      tags:
      - users
      description: "Directly inserts a message into only this user's mailbox similar\
        \ to `IMAP APPEND`, bypassing most scanning and classification. Does not send\
        \ a message."
      operationId: gmail.users.messages.insert
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.insert
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.insert
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
  /users/{userId}/messages/batchDelete:
    post:
      tags:
      - users
      description: Deletes many messages by message ID. Provides no guarantees that
        messages were not already deleted or even existed at all.
      operationId: gmail.users.messages.batchDelete
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
  /users/{userId}/messages/batchModify:
    post:
      tags:
      - users
      description: Modifies the labels on the specified messages.
      operationId: gmail.users.messages.batchModify
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
  /users/{userId}/messages/import:
    post:
      tags:
      - users
      description: "Imports a message into only this user's mailbox, with standard\
        \ email delivery scanning and classification similar to receiving via SMTP.\
        \ This method doesn't perform SPF checks, so it might not work for some spam\
        \ messages, such as those attempting to perform domain spoofing. This method\
        \ does not send a message."
      operationId: gmail.users.messages.import
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.insert
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.insert
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
  /users/{userId}/messages/send:
    post:
      tags:
      - users
      description: "Sends the specified message to the recipients in the `To`, `Cc`,\
        \ and `Bcc` headers. For example usage, see [Sending email](https://developers.google.com/gmail/api/guides/sending)."
      operationId: gmail.users.messages.send
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.addons.current.action.compose
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.addons.current.action.compose
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.compose
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.compose
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.send
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.send
  /users/{userId}/messages/{id}:
    get:
      tags:
      - users
      description: Gets the specified message.
      operationId: gmail.users.messages.get
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.addons.current.message.action
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.addons.current.message.action
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.addons.current.message.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.addons.current.message.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.addons.current.message.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.addons.current.message.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.readonly
    delete:
      tags:
      - users
      description: Immediately and permanently deletes the specified message. This
        operation cannot be undone. Prefer `messages.trash` instead.
      operationId: gmail.users.messages.delete
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
  /users/{userId}/messages/{id}/modify:
    post:
      tags:
      - users
      description: Modifies the labels on the specified message.
      operationId: gmail.users.messages.modify
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
  /users/{userId}/messages/{id}/trash:
    post:
      tags:
      - users
      description: Moves the specified message to the trash.
      operationId: gmail.users.messages.trash
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
  /users/{userId}/messages/{id}/untrash:
    post:
      tags:
      - users
      description: Removes the specified message from the trash.
      operationId: gmail.users.messages.untrash
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
  /users/{userId}/messages/{messageId}/attachments/{id}:
    get:
      tags:
      - users
      description: Gets the specified message attachment.
      operationId: gmail.users.messages.attachments.get
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.addons.current.message.action
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.addons.current.message.action
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.addons.current.message.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.addons.current.message.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.readonly
  /users/{userId}/profile:
    get:
      tags:
      - users
      description: Gets the current user's Gmail profile.
      operationId: gmail.users.getProfile
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.compose
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.compose
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.readonly
  /users/{userId}/threads:
    get:
      tags:
      - users
      description: Lists the threads in the user's mailbox.
      operationId: gmail.users.threads.list
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.readonly
  /users/{userId}/threads/{id}:
    get:
      tags:
      - users
      description: Gets the specified thread.
      operationId: gmail.users.threads.get
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.addons.current.message.action
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.addons.current.message.action
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.addons.current.message.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.addons.current.message.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.addons.current.message.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.addons.current.message.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.metadata
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.metadata
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.readonly
    delete:
      tags:
      - users
      description: Immediately and permanently deletes the specified thread. Any messages
        that belong to the thread are also deleted. This operation cannot be undone.
        Prefer `threads.trash` instead.
      operationId: gmail.users.threads.delete
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
  /users/{userId}/threads/{id}/modify:
    post:
      tags:
      - users
      description: Modifies the labels applied to the thread. This applies to all
        messages in the thread.
      operationId: gmail.users.threads.modify
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
  /users/{userId}/threads/{id}/trash:
    post:
      tags:
      - users
      description: Moves the specified thread to the trash. Any messages that belong
        to the thread are also moved to the trash.
      operationId: gmail.users.threads.trash
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
  /users/{userId}/threads/{id}/untrash:
    post:
      tags:
      - users
      description: Removes the specified thread from the trash. Any messages that
        belong to the thread are also removed from the trash.
      operationId: gmail.users.threads.untrash
      security:
      - Oauth2:
        - https://mail.google.com/
        Oauth2c:
        - https://mail.google.com/
      - Oauth2:
        - https://www.googleapis.com/auth/gmail.modify
        Oauth2c:
        - https://www.googleapis.com/auth/gmail.modify
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://mail.google.com/: "Read, compose, send, and permanently delete\
              \ all your email from Gmail"
            https://www.googleapis.com/auth/gmail.addons.current.action.compose: Manage
              drafts and send emails when you interact with the add-on
            https://www.googleapis.com/auth/gmail.addons.current.message.action: View
              your email messages when you interact with the add-on
            https://www.googleapis.com/auth/gmail.addons.current.message.metadata: View
              your email message metadata when the add-on is running
            https://www.googleapis.com/auth/gmail.addons.current.message.readonly: View
              your email messages when the add-on is running
            https://www.googleapis.com/auth/gmail.compose: Manage drafts and send
              emails
            https://www.googleapis.com/auth/gmail.insert: Add emails into your Gmail
              mailbox
            https://www.googleapis.com/auth/gmail.labels: See and edit your email
              labels
            https://www.googleapis.com/auth/gmail.metadata: "View your email message\
              \ metadata such as labels and headers, but not the email body"
            https://www.googleapis.com/auth/gmail.modify: "Read, compose, and send\
              \ emails from your Gmail account"
            https://www.googleapis.com/auth/gmail.readonly: View your email messages
              and settings
            https://www.googleapis.com/auth/gmail.send: Send email on your behalf
            https://www.googleapis.com/auth/gmail.settings.basic: "See, edit, create,\
              \ or change your email settings and filters in Gmail"
            https://www.googleapis.com/auth/gmail.settings.sharing: "Manage your sensitive\
              \ mail settings, including who can manage your mail"
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes:
            https://mail.google.com/: "Read, compose, send, and permanently delete\
              \ all your email from Gmail"
            https://www.googleapis.com/auth/gmail.addons.current.action.compose: Manage
              drafts and send emails when you interact with the add-on
            https://www.googleapis.com/auth/gmail.addons.current.message.action: View
              your email messages when you interact with the add-on
            https://www.googleapis.com/auth/gmail.addons.current.message.metadata: View
              your email message metadata when the add-on is running
            https://www.googleapis.com/auth/gmail.addons.current.message.readonly: View
              your email messages when the add-on is running
            https://www.googleapis.com/auth/gmail.compose: Manage drafts and send
              emails
            https://www.googleapis.com/auth/gmail.insert: Add emails into your Gmail
              mailbox
            https://www.googleapis.com/auth/gmail.labels: See and edit your email
              labels
            https://www.googleapis.com/auth/gmail.metadata: "View your email message\
              \ metadata such as labels and headers, but not the email body"
            https://www.googleapis.com/auth/gmail.modify: "Read, compose, and send\
              \ emails from your Gmail account"
            https://www.googleapis.com/auth/gmail.readonly: View your email messages
              and settings
            https://www.googleapis.com/auth/gmail.send: Send email on your behalf
            https://www.googleapis.com/auth/gmail.settings.basic: "See, edit, create,\
              \ or change your email settings and filters in Gmail"
            https://www.googleapis.com/auth/gmail.settings.sharing: "Manage your sensitive\
              \ mail settings, including who can manage your mail"
x-hasEquivalentPaths: true
