name: CI

on:
  push:
    branches-ignore:
      - "automated/dependency_version_update"
      - "automated/dependency_version_update_tmp"
  repository_dispatch:
    types:
      check_connector_for_breaking_changes

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@2201.2.1
              with:
                  args:
                      pack
              env:
                WORKING_DIR: ./gmail
            - name: Ballerina Tests
              uses: ballerina-platform/ballerina-action/@2201.2.1
              with:
                  args:
                      test --code-coverage
              env:
                  WORKING_DIR: ./gmail
                  JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
                  CLIENT_ID: ${{ secrets.CLIENT_ID }} 
                  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }} 
                  REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
                  REFRESH_URL: ${{ secrets.REFRESH_URL }}
                  RECIPIENT: ${{ secrets.RECIPIENT }}
                  SENDER: ${{ secrets.SENDER }}
                  CC: ${{ secrets.CC }}
                  ATTACHMENT_PATH: ${{ secrets.ATTACHMENT_PATH }}
                  ATTACHMENT_CONTENT_TYPE: ${{ secrets.ATTACHMENT_CONTENT_TYPE }}
                  INLINE_IMAGE_PATH: ${{ secrets.INLINE_IMAGE_PATH }}
                  INLINE_IMAGE_NAME: ${{ secrets.INLINE_IMAGE_NAME }}
                  IMAGE_CONTENT_TYPE: ${{ secrets.IMAGE_CONTENT_TYPE }}

            # Read the ballerina test results
            - name: Read Ballerina Test Results
              id: test_results
              run: |
                  content=`cat ./gmail/target/report/test_results.json`                
                  content="${content//'%'/'%25'}"
                  content="${content//$'\n'/'%0A'}"
                  content="${content//$'\r'/'%0D'}"
                  echo "::set-output name=testResultsJson::$content"

            # Print the code coverage information
            - name: Code Coverage
              run: |
                  echo "Covered Code Lines : ${{fromJson(steps.test_results.outputs.testResultsJson).coveredLines}}"
                  echo "Total Code Lines : $(expr ${{fromJson(steps.test_results.outputs.testResultsJson).missedLines}} + ${{fromJson(steps.test_results.outputs.testResultsJson).coveredLines}})"
                  echo "Code Coverage Percentage : ${{fromJson(steps.test_results.outputs.testResultsJson).coveragePercentage}}"

            - name: Alert notifier on failure
              if: failure() && (github.event.action == 'check_connector_for_breaking_changes')
              run: |
                curl -X POST \
                'https://api.github.com/repos/ballerina-platform/ballerina-release/dispatches' \
                --header 'Accept: application/vnd.github.v3+json' \
                --header 'Authorization: Bearer ${{ secrets.BALLERINA_BOT_TOKEN }}' \
                --data-raw '{
                  "event_type": "notify-ballerinax-connector-build-failure",
                  "client_payload": {
                    "repoName": "module-ballerinax-googleapis.gmail",
                    "workflow": "CI"
                  }
                }'
