name: Pull_Request

on: [pull_request]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@2201.6.0
              with:
                  args:
                      pack
              env:
                WORKING_DIR: ./gmail
